version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend-docker
    restart: always
    links:
      - backend

  backend:
    build: ./backend
    ports:
      - 3001:3001
    container_name: backend-docker
    restart: always
    links:
      - db

  db:
    image: mysql:8.0.21
    ports:
    - 3306:3306
    container_name: database-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password